// This file is automatically generated.
import request from './request'

export type DateTime = string
export type Decimal = number

export default {
  books: {
    hello(): Promise<{message: string}>{ return request('get', '/books/hello', {}) },
  },
}
