// This file is automatically generated.
import request from './request'

export type Book = {id: number, name: string, author: string, retailPrice: Decimal, createdAt: DateTime, updatedAt: DateTime}
export type Book_Params = Omit<Book, "id" | "createdAt" | "updatedAt">
export type DateTime = string
export type Decimal = string

export default {
  books: {
    hello(): Promise<{message: string}>{ return request('get', '/books/hello', {}) },
    create(params: {book: Book_Params}): Promise<boolean>{ return request('post', '/books/create', params) },
    show(params: {id: number}): Promise<{book: Book}>{ return request('get', '/books/show', params) },
  },
}
